[workspace]
members = [
    "crates/jam",
    "crates/jam-llvm",
    "crates/jam-core",
    "crates/jam-syntax",
    "crates/jam-sema",
    "crates/float128",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2024"
license = "Apache-2.0 WITH LLVM-exception"
keywords = ["compiler"]
rust-version = "1.96.0"
repository = "https://github.com/raphamorim/jam"
homepage = "https://jamlang.org"
documentation = "https://github.com/raphamorim/jam#readme"
readme = "README.md"

[workspace.dependencies]
