[package]
name = "jam_llvm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Jam programming language compiler llvm bindings"
build = "build.rs"

[lib]
name = "jam_llvm"
path = "src/lib.rs"

[dependencies]
jam_core = { path = "../jam-core" }
float128 = { path = "../float128" }

[build-dependencies]
cc = "1.2.64"
